fname = input("first name : ")
lname = input("last name : ")
mark = int(input("grade(9-12) : "))
id = int(input("student id : "))
login = input("login : ")
cgpa = float(input("GPA(0.0-4.0) : "))
print("\n")
print("YOUR INFORMATION \n")
print(f"\tLogin : {login}")
print(f"\tId : {id}")
print(f"\tName : {fname}{lname}")
print(f"\tGPA :{cgpa}")
print(f"\tGrade : {mark}")